name: CI

on:
   push:
     branches:
       - main
   pull_request:

env:
  doc_name: main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install latex
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends make texlive-plain-generic texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-science texlive-fonts-recommended texlive-fonts-extra texlive-bibtex-extra texlive-extra-utils biber latexmk
    - name: Build document
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.doc_name }}.pdf
        path: output/${{ env.doc_name }}.pdf

